#!/bin/bash
DEVELOPMENT=master
PRODUCTION=themes
FILES=()
ASSETS=()


git checkout $DEVELOPMENT
for file in themes/*; do
  if [ -f "$file" ]; then
    FILES+=($file);
  fi
done
for file in themes/assets/*; do
  if [ -f "$file" ]; then
    ASSETS+=($file);
  fi
done

git checkout $PRODUCTION

for file in "${FILES[@]}"; do
  BASENAME=`basename $file`;
  git show master:$file > $BASENAME;
done
for file in "${ASSETS[@]}"; do
  BASENAME=`basename $file`;
  git show master:$file > assets/$BASENAME;
done

git pull
git commit -am $1
git push production
